#include "RuleManager.h"
#include <string.h>
namespace { constexpr size_t INVALID_INDEX_VALUE=RULE_MANAGER_CAPACITY; }
RuleManager::RuleManager():rules_{},count_(0){} void RuleManager::clear(){for(size_t i=0;i<RULE_MANAGER_CAPACITY;++i)rules_[i]=Rule{};count_=0;}
AutomationModelResult RuleManager::add(const Rule& v){if(!v.isValid())return AutomationModelResult::INVALID_MODEL;if(isFull())return AutomationModelResult::CAPACITY_FULL;if(contains(v.id))return AutomationModelResult::DUPLICATE_ID;if(findByName(v.name))return AutomationModelResult::DUPLICATE_NAME;rules_[count_++]=v;return AutomationModelResult::SUCCESS;}
AutomationModelResult RuleManager::update(const Rule& v){if(!v.isValid())return AutomationModelResult::INVALID_MODEL;size_t i=findIndexById(v.id);if(i==INVALID_INDEX_VALUE)return AutomationModelResult::NOT_FOUND;if(nameBelongsToAnother(v.name,v.id))return AutomationModelResult::DUPLICATE_NAME;rules_[i]=v;return AutomationModelResult::SUCCESS;}
AutomationModelResult RuleManager::remove(RuleId id){if(id==INVALID_RULE_ID)return AutomationModelResult::INVALID_ID;size_t i=findIndexById(id);if(i==INVALID_INDEX_VALUE)return AutomationModelResult::NOT_FOUND;for(size_t j=i+1U;j<count_;++j)rules_[j-1U]=rules_[j];--count_;rules_[count_]=Rule{};return AutomationModelResult::SUCCESS;}
size_t RuleManager::findIndexById(RuleId id)const{if(id==INVALID_RULE_ID)return INVALID_INDEX_VALUE;for(size_t i=0;i<count_;++i)if(rules_[i].id==id)return i;return INVALID_INDEX_VALUE;}
const Rule* RuleManager::findById(RuleId id)const{size_t i=findIndexById(id);return i==INVALID_INDEX_VALUE?nullptr:&rules_[i];}const Rule* RuleManager::findByName(const char* n)const{if(!n||n[0]=='\0')return nullptr;for(size_t i=0;i<count_;++i)if(strcmp(rules_[i].name,n)==0)return &rules_[i];return nullptr;}const Rule* RuleManager::getAt(size_t i)const{return i<count_?&rules_[i]:nullptr;}bool RuleManager::contains(RuleId id)const{return findIndexById(id)!=INVALID_INDEX_VALUE;}bool RuleManager::nameBelongsToAnother(const char* n,RuleId id)const{const Rule* p=findByName(n);return p&&p->id!=id;}size_t RuleManager::size()const{return count_;}size_t RuleManager::capacity()const{return RULE_MANAGER_CAPACITY;}bool RuleManager::isFull()const{return count_>=RULE_MANAGER_CAPACITY;}bool RuleManager::isEmpty()const{return count_==0U;}
