#include <unity.h>
#include <type_traits>
#include <MainController.h>

class FakeComponentPort final:public MainControllerComponentPort
{public:explicit FakeComponentPort(MainControllerComponent c,bool critical=false,bool begin=true,bool update=true):component_(c),critical_(critical),hasBegin_(begin),hasUpdate_(update){}MainControllerComponent component_;bool critical_,hasBegin_,hasUpdate_;MainControllerResult beginResult=MainControllerResult::SUCCESS,updateResult=MainControllerResult::NO_CHANGE;size_t beginCalls=0U,updateCalls=0U;MainControllerTimestamp beginNow=99U,updateNow=0U;size_t* sequence=nullptr;size_t beginAt=0U,updateAt=0U;MainController* reenter=nullptr;MainControllerResult nestedResult=MainControllerResult::SUCCESS;MainControllerComponent component()const override{return component_;}bool critical()const override{return critical_;}bool hasBegin()const override{return hasBegin_;}bool hasUpdate()const override{return hasUpdate_;}MainControllerResult begin(MainControllerTimestamp now)override{++beginCalls;beginNow=now;if(sequence!=nullptr)beginAt=++(*sequence);return beginResult;}MainControllerResult update(MainControllerTimestamp now)override{++updateCalls;updateNow=now;if(sequence!=nullptr)updateAt=++(*sequence);if(reenter!=nullptr)nestedResult=reenter->update(now);return updateResult;}};
class MainControllerTestAccess{public:static void saturateCycle(MainController& c){c.cycleCount_=UINT32_MAX;}static void saturateState(MainController& c,MainControllerComponent id){MainControllerRuntimeState& s=c.states_[static_cast<size_t>(id)];s.updateCount_=UINT32_MAX;s.failureCount_=UINT32_MAX;s.consecutiveFailureCount_=UINT32_MAX;}static MainControllerResult combine(MainControllerResult a,MainControllerResult b){return MainController::combine(a,b);}};
static void assertResult(MainControllerResult expected,MainControllerResult actual){TEST_ASSERT_EQUAL_UINT8(static_cast<uint8_t>(expected),static_cast<uint8_t>(actual));}

void test_default_state_dependency_registration_and_invalid_update()
{MainControllerDependencies dependencies;FakeComponentPort communication(MainControllerComponent::COMMUNICATION);TEST_ASSERT_TRUE(dependencies.set(communication));TEST_ASSERT_FALSE(dependencies.set(communication));MainController controller(dependencies);TEST_ASSERT_FALSE(controller.isInitialized());TEST_ASSERT_FALSE(controller.isUpdating());TEST_ASSERT_FALSE(controller.isDegraded());TEST_ASSERT_EQUAL_UINT32(1U,controller.componentCount());assertResult(MainControllerResult::NOT_INITIALIZED,controller.lastResult());assertResult(MainControllerResult::NOT_INITIALIZED,controller.update(10U));TEST_ASSERT_EQUAL_UINT32(0U,communication.updateCalls);TEST_ASSERT_NULL(controller.state(MainControllerComponent::NODE));TEST_ASSERT_NOT_NULL(controller.state(MainControllerComponent::COMMUNICATION));}
void test_begin_order_passive_lifecycle_and_rebegin()
{MainControllerDependencies d;FakeComponentPort config(MainControllerComponent::CONFIGURATION,true,true,false),event(MainControllerComponent::EVENT,true,true,true),adapter(MainControllerComponent::EVENT_TO_NOTIFICATION,false,true,false),communication(MainControllerComponent::COMMUNICATION);size_t sequence=0U;config.sequence=event.sequence=adapter.sequence=communication.sequence=&sequence;d.set(communication);d.set(adapter);d.set(event);d.set(config);MainController c(d);assertResult(MainControllerResult::SUCCESS,c.begin());TEST_ASSERT_TRUE(c.isInitialized());TEST_ASSERT_EQUAL_UINT32(1U,config.beginAt);TEST_ASSERT_EQUAL_UINT32(2U,event.beginAt);TEST_ASSERT_EQUAL_UINT32(3U,adapter.beginAt);TEST_ASSERT_EQUAL_UINT32(4U,communication.beginAt);TEST_ASSERT_EQUAL_UINT32(0U,config.beginNow);TEST_ASSERT_TRUE(c.state(MainControllerComponent::EVENT_TO_NOTIFICATION)->initialized());assertResult(MainControllerResult::SUCCESS,c.begin());TEST_ASSERT_EQUAL_UINT32(2U,config.beginCalls);TEST_ASSERT_EQUAL_UINT32(0U,adapter.updateCalls);}
void test_critical_and_recoverable_begin_failures()
{{MainControllerDependencies d;FakeComponentPort config(MainControllerComponent::CONFIGURATION,true);FakeComponentPort logger(MainControllerComponent::LOGGER,false);config.beginResult=MainControllerResult::COMPONENT_FAILED;d.set(config);d.set(logger);MainController c(d);assertResult(MainControllerResult::INITIALIZATION_FAILED,c.begin());TEST_ASSERT_FALSE(c.isInitialized());TEST_ASSERT_EQUAL_UINT32(1U,logger.beginCalls);} {MainControllerDependencies d;FakeComponentPort config(MainControllerComponent::CONFIGURATION,true);FakeComponentPort logger(MainControllerComponent::LOGGER,false);logger.beginResult=MainControllerResult::DEGRADED;d.set(config);d.set(logger);MainController c(d);assertResult(MainControllerResult::DEGRADED,c.begin());TEST_ASSERT_TRUE(c.isInitialized());TEST_ASSERT_TRUE(c.isDegraded());}}
void test_update_order_explicit_time_once_and_passive_not_polled()
{MainControllerDependencies d;FakeComponentPort communication(MainControllerComponent::COMMUNICATION),command(MainControllerComponent::COMMAND_EXECUTION),node(MainControllerComponent::NODE),scheduler(MainControllerComponent::SCHEDULER),rule(MainControllerComponent::RULE),scene(MainControllerComponent::SCENE),event(MainControllerComponent::EVENT),adapter(MainControllerComponent::EVENT_TO_NOTIFICATION,false,true,false),notification(MainControllerComponent::NOTIFICATION),logger(MainControllerComponent::LOGGER),storage(MainControllerComponent::STORAGE);FakeComponentPort* ports[]={&communication,&command,&node,&scheduler,&rule,&scene,&event,&adapter,&notification,&logger,&storage};size_t sequence=0U;for(size_t i=0U;i<sizeof(ports)/sizeof(ports[0]);++i){ports[i]->sequence=&sequence;d.set(*ports[i]);}MainController c(d);c.begin();sequence=0U;communication.updateResult=MainControllerResult::SUCCESS;assertResult(MainControllerResult::SUCCESS,c.update(1234U));TEST_ASSERT_EQUAL_UINT32(1U,communication.updateAt);TEST_ASSERT_EQUAL_UINT32(2U,command.updateAt);TEST_ASSERT_EQUAL_UINT32(3U,node.updateAt);TEST_ASSERT_EQUAL_UINT32(4U,scheduler.updateAt);TEST_ASSERT_EQUAL_UINT32(5U,rule.updateAt);TEST_ASSERT_EQUAL_UINT32(6U,scene.updateAt);TEST_ASSERT_EQUAL_UINT32(7U,event.updateAt);TEST_ASSERT_EQUAL_UINT32(8U,notification.updateAt);TEST_ASSERT_EQUAL_UINT32(9U,logger.updateAt);TEST_ASSERT_EQUAL_UINT32(10U,storage.updateAt);TEST_ASSERT_EQUAL_UINT32(1234U,notification.updateNow);TEST_ASSERT_EQUAL_UINT32(0U,adapter.updateCalls);for(size_t i=0U;i<sizeof(ports)/sizeof(ports[0]);++i)if(ports[i]!=&adapter)TEST_ASSERT_EQUAL_UINT32(1U,ports[i]->updateCalls);TEST_ASSERT_EQUAL_UINT32(1U,c.cycleCount());}
void test_aggregation_priority_and_unknown_fail_closed()
{const MainControllerResult ordered[]={MainControllerResult::NO_CHANGE,MainControllerResult::SUCCESS,MainControllerResult::IN_PROGRESS,MainControllerResult::RETRY_LATER,MainControllerResult::DEGRADED,MainControllerResult::COMPONENT_FAILED,MainControllerResult::INTERNAL_ERROR};for(size_t i=1U;i<sizeof(ordered)/sizeof(ordered[0]);++i)assertResult(ordered[i],MainControllerTestAccess::combine(ordered[i-1U],ordered[i]));assertResult(MainControllerResult::INTERNAL_ERROR,MainControllerTestAccess::combine(MainControllerResult::SUCCESS,static_cast<MainControllerResult>(255U)));MainControllerDependencies d;FakeComponentPort communication(MainControllerComponent::COMMUNICATION),scheduler(MainControllerComponent::SCHEDULER);d.set(communication);d.set(scheduler);MainController c(d);c.begin();communication.updateResult=MainControllerResult::SUCCESS;scheduler.updateResult=MainControllerResult::RETRY_LATER;assertResult(MainControllerResult::RETRY_LATER,c.update(1U));communication.updateResult=MainControllerResult::COMPONENT_FAILED;scheduler.updateResult=MainControllerResult::IN_PROGRESS;assertResult(MainControllerResult::COMPONENT_FAILED,c.update(2U));communication.updateResult=static_cast<MainControllerResult>(200U);scheduler.updateResult=MainControllerResult::SUCCESS;assertResult(MainControllerResult::INTERNAL_ERROR,c.update(3U));}
void test_failure_isolation_and_health_tracking()
{MainControllerDependencies d;FakeComponentPort communication(MainControllerComponent::COMMUNICATION),scheduler(MainControllerComponent::SCHEDULER),notification(MainControllerComponent::NOTIFICATION);d.set(communication);d.set(scheduler);d.set(notification);MainController c(d);c.begin();communication.updateResult=MainControllerResult::DEGRADED;scheduler.updateResult=MainControllerResult::SUCCESS;notification.updateResult=MainControllerResult::IN_PROGRESS;assertResult(MainControllerResult::DEGRADED,c.update(100U));TEST_ASSERT_EQUAL_UINT32(1U,scheduler.updateCalls);TEST_ASSERT_EQUAL_UINT32(1U,notification.updateCalls);const MainControllerRuntimeState* comm=c.state(MainControllerComponent::COMMUNICATION);TEST_ASSERT_EQUAL_UINT32(1U,comm->updateCount());TEST_ASSERT_EQUAL_UINT32(1U,comm->failureCount());TEST_ASSERT_EQUAL_UINT32(1U,comm->consecutiveFailureCount());TEST_ASSERT_EQUAL_UINT32(100U,comm->lastUpdateAt());communication.updateResult=MainControllerResult::SUCCESS;assertResult(MainControllerResult::IN_PROGRESS,c.update(200U));TEST_ASSERT_EQUAL_UINT32(0U,comm->consecutiveFailureCount());TEST_ASSERT_EQUAL_UINT32(200U,comm->lastSuccessAt());communication.updateResult=MainControllerResult::NO_CHANGE;c.update(300U);TEST_ASSERT_EQUAL_UINT32(0U,comm->consecutiveFailureCount());}
void test_reentrant_update_rejected_and_guard_recovers()
{MainControllerDependencies d;FakeComponentPort event(MainControllerComponent::EVENT);d.set(event);MainController c(d);c.begin();event.reenter=&c;event.updateResult=MainControllerResult::SUCCESS;assertResult(MainControllerResult::SUCCESS,c.update(50U));assertResult(MainControllerResult::ALREADY_UPDATING,event.nestedResult);TEST_ASSERT_EQUAL_UINT32(1U,event.updateCalls);TEST_ASSERT_FALSE(c.isUpdating());event.reenter=nullptr;event.updateResult=MainControllerResult::INTERNAL_ERROR;assertResult(MainControllerResult::INTERNAL_ERROR,c.update(60U));TEST_ASSERT_FALSE(c.isUpdating());event.updateResult=MainControllerResult::SUCCESS;assertResult(MainControllerResult::SUCCESS,c.update(70U));TEST_ASSERT_EQUAL_UINT32(3U,event.updateCalls);}
void test_counter_saturation_and_fixed_state_capacity()
{MainControllerDependencies d;FakeComponentPort node(MainControllerComponent::NODE);d.set(node);MainController c(d);c.begin();MainControllerTestAccess::saturateCycle(c);MainControllerTestAccess::saturateState(c,MainControllerComponent::NODE);node.updateResult=MainControllerResult::COMPONENT_FAILED;c.update(UINT32_MAX);const MainControllerRuntimeState* state=c.state(MainControllerComponent::NODE);TEST_ASSERT_EQUAL_UINT32(UINT32_MAX,c.cycleCount());TEST_ASSERT_EQUAL_UINT32(UINT32_MAX,state->updateCount());TEST_ASSERT_EQUAL_UINT32(UINT32_MAX,state->failureCount());TEST_ASSERT_EQUAL_UINT32(UINT32_MAX,state->consecutiveFailureCount());TEST_ASSERT_EQUAL_UINT32(MAIN_CONTROLLER_COMPONENT_COUNT,static_cast<size_t>(MainControllerComponent::COUNT));}

static_assert(std::is_abstract<MainControllerComponentPort>::value,"orchestration seam");
void setup(){UNITY_BEGIN();RUN_TEST(test_default_state_dependency_registration_and_invalid_update);RUN_TEST(test_begin_order_passive_lifecycle_and_rebegin);RUN_TEST(test_critical_and_recoverable_begin_failures);RUN_TEST(test_update_order_explicit_time_once_and_passive_not_polled);RUN_TEST(test_aggregation_priority_and_unknown_fail_closed);RUN_TEST(test_failure_isolation_and_health_tracking);RUN_TEST(test_reentrant_update_rejected_and_guard_recovers);RUN_TEST(test_counter_saturation_and_fixed_state_capacity);UNITY_END();}void loop(){}
