#include <unity.h>
#include <type_traits>
#include <NotificationRuntime.h>

class FakeNotificationSink final:public NotificationSink
{
public:
 NotificationSinkResult sendResult=NotificationSinkResult::SUCCESS;
 NotificationSinkResult updateResult=NotificationSinkResult::SUCCESS;
 NotificationSinkResult cancelResult=NotificationSinkResult::SUCCESS;
 size_t sendCalls=0U,updateCalls=0U,cancelCalls=0U;
 NotificationId lastNotificationId=0U;NotificationChannelId lastChannelId=0U;
 const uint8_t* lastPayload=nullptr;size_t lastPayloadLength=0U;
 const char* lastTarget=nullptr;size_t lastTargetLength=0U;
 const NotificationChannelDescriptor* lastDescriptor=nullptr;
 NotificationSinkResult sendNotification(const NotificationMessage& message,const NotificationChannelDescriptor& channel)override
 {++sendCalls;lastNotificationId=message.notificationId();lastChannelId=channel.channelId();lastPayload=message.payload();lastPayloadLength=message.payloadLength();lastTarget=message.target();lastTargetLength=message.targetLength();lastDescriptor=&channel;return sendResult;}
 NotificationSinkResult updateNotificationSend(NotificationChannelId id)override{++updateCalls;lastChannelId=id;return updateResult;}
 NotificationSinkResult cancelNotificationSend(NotificationChannelId id)override{++cancelCalls;lastChannelId=id;return cancelResult;}
};

static NotificationChannelDescriptor descriptor(NotificationChannelId id,bool enabled=true,NotificationChannelType type=NotificationChannelType::GENERIC)
{return NotificationChannelDescriptor::create(id,type,enabled);}
static NotificationMessage message(NotificationId id=10U,NotificationChannelId channel=1U,NotificationTimestamp created=100U,NotificationDuration ttl=50U)
{static const char target[]={'u','s','e','r'};static const uint8_t payload[]={0x41U,0x00U,0xFFU};return NotificationMessage::create(id,channel,NotificationPriority::NORMAL,created,ttl,target,sizeof(target),payload,sizeof(payload));}
static void assertResult(NotificationRuntimeResult expected,NotificationRuntimeResult actual)
{TEST_ASSERT_EQUAL_UINT8(static_cast<uint8_t>(expected),static_cast<uint8_t>(actual));}

void test_message_default_validation_bounds_and_views()
{
 NotificationMessage empty;TEST_ASSERT_FALSE(empty.isValid());const char target[]={'a','b'};const uint8_t payload[]={1U,0U,2U};
 TEST_ASSERT_FALSE(NotificationMessage::create(0U,1U,NotificationPriority::LOW_PRIORITY,0U,1U,target,2U,payload,3U).isValid());
 TEST_ASSERT_FALSE(NotificationMessage::create(1U,0U,NotificationPriority::LOW_PRIORITY,0U,1U,target,2U,payload,3U).isValid());
 TEST_ASSERT_FALSE(NotificationMessage::create(1U,1U,NotificationPriority::COUNT,0U,1U,target,2U,payload,3U).isValid());
 TEST_ASSERT_FALSE(NotificationMessage::create(1U,1U,NotificationPriority::HIGH_PRIORITY,0U,0U,target,2U,payload,3U).isValid());
 TEST_ASSERT_FALSE(NotificationMessage::create(1U,1U,NotificationPriority::HIGH_PRIORITY,0U,1U,nullptr,2U,payload,3U).isValid());
 TEST_ASSERT_FALSE(NotificationMessage::create(1U,1U,NotificationPriority::HIGH_PRIORITY,0U,1U,target,0U,payload,3U).isValid());
 TEST_ASSERT_FALSE(NotificationMessage::create(1U,1U,NotificationPriority::HIGH_PRIORITY,0U,1U,target,NOTIFICATION_RUNTIME_MAX_TARGET_LENGTH+1U,payload,3U).isValid());
 TEST_ASSERT_FALSE(NotificationMessage::create(1U,1U,NotificationPriority::HIGH_PRIORITY,0U,1U,target,2U,nullptr,3U).isValid());
 TEST_ASSERT_FALSE(NotificationMessage::create(1U,1U,NotificationPriority::HIGH_PRIORITY,0U,1U,target,2U,payload,0U).isValid());
 TEST_ASSERT_FALSE(NotificationMessage::create(1U,1U,NotificationPriority::HIGH_PRIORITY,0U,1U,target,2U,payload,NOTIFICATION_RUNTIME_MAX_PAYLOAD_LENGTH+1U).isValid());
 NotificationMessage valid=NotificationMessage::create(7U,3U,NotificationPriority::CRITICAL,9U,11U,target,2U,payload,3U);TEST_ASSERT_TRUE(valid.isValid());TEST_ASSERT_EQUAL_UINT32(7U,valid.notificationId());TEST_ASSERT_EQUAL_UINT8(3U,valid.channelId());TEST_ASSERT_EQUAL_UINT8(static_cast<uint8_t>(NotificationPriority::CRITICAL),static_cast<uint8_t>(valid.priority()));TEST_ASSERT_EQUAL_UINT32(9U,valid.createdAt());TEST_ASSERT_EQUAL_UINT32(11U,valid.ttlMs());TEST_ASSERT_EQUAL_PTR(target,valid.target());TEST_ASSERT_EQUAL_UINT32(2U,valid.targetLength());TEST_ASSERT_EQUAL_PTR(payload,valid.payload());TEST_ASSERT_EQUAL_UINT32(3U,valid.payloadLength());
}
void test_message_expiration_threshold_and_wraparound()
{NotificationMessage normal=message(1U,1U,100U,50U);TEST_ASSERT_FALSE(normal.isExpired(149U));TEST_ASSERT_TRUE(normal.isExpired(150U));TEST_ASSERT_TRUE(normal.isExpired(151U));NotificationMessage wrapped=message(2U,1U,0xFFFFFFF0U,32U);TEST_ASSERT_FALSE(wrapped.isExpired(0x0000000FU));TEST_ASSERT_TRUE(wrapped.isExpired(0x00000010U));}
void test_descriptor_and_enum_validation()
{NotificationChannelDescriptor empty;TEST_ASSERT_FALSE(empty.isValid());TEST_ASSERT_FALSE(descriptor(0U).isValid());TEST_ASSERT_FALSE(descriptor(1U,true,NotificationChannelType::COUNT).isValid());NotificationChannelDescriptor enabled=descriptor(2U,true,NotificationChannelType::SMS);TEST_ASSERT_TRUE(enabled.isValid());TEST_ASSERT_EQUAL_UINT8(2U,enabled.channelId());TEST_ASSERT_EQUAL_UINT8(static_cast<uint8_t>(NotificationChannelType::SMS),static_cast<uint8_t>(enabled.channelType()));TEST_ASSERT_TRUE(enabled.enabled());TEST_ASSERT_FALSE(descriptor(3U,false).enabled());TEST_ASSERT_FALSE(isValidNotificationSinkResult(static_cast<NotificationSinkResult>(255U)));TEST_ASSERT_FALSE(isValidNotificationRuntimeResult(NotificationRuntimeResult::COUNT));}
void test_registry_registration_lookup_capacity_lock_and_atomicity()
{NotificationRegistry registry;FakeNotificationSink sinks[NOTIFICATION_RUNTIME_MAX_CHANNELS];TEST_ASSERT_EQUAL_UINT32(0U,registry.size());TEST_ASSERT_EQUAL_UINT32(NOTIFICATION_RUNTIME_MAX_CHANNELS,registry.capacity());assertResult(NotificationRuntimeResult::INVALID_CHANNEL,registry.registerChannel(NotificationChannelDescriptor{},sinks[0]));TEST_ASSERT_EQUAL_UINT32(0U,registry.size());NotificationChannelDescriptor original=descriptor(1U,true,NotificationChannelType::SMS);assertResult(NotificationRuntimeResult::SUCCESS,registry.registerChannel(original,sinks[0]));assertResult(NotificationRuntimeResult::DUPLICATE_CHANNEL_ID,registry.registerChannel(original,sinks[1]));TEST_ASSERT_EQUAL_UINT32(1U,registry.size());TEST_ASSERT_NOT_NULL(registry.findDescriptor(1U));TEST_ASSERT_EQUAL_PTR(&sinks[0],registry.findSink(1U));TEST_ASSERT_NULL(registry.findDescriptor(0U));TEST_ASSERT_NULL(registry.findSink(99U));for(size_t i=1U;i<NOTIFICATION_RUNTIME_MAX_CHANNELS;++i)assertResult(NotificationRuntimeResult::SUCCESS,registry.registerChannel(descriptor(static_cast<NotificationChannelId>(i+1U)),sinks[i]));assertResult(NotificationRuntimeResult::REGISTRY_FULL,registry.registerChannel(descriptor(20U),sinks[0]));TEST_ASSERT_EQUAL_UINT32(NOTIFICATION_RUNTIME_MAX_CHANNELS,registry.size());assertResult(NotificationRuntimeResult::SUCCESS,registry.lock());TEST_ASSERT_TRUE(registry.isLocked());assertResult(NotificationRuntimeResult::REGISTRY_LOCKED,registry.registerChannel(descriptor(21U),sinks[0]));TEST_ASSERT_EQUAL_UINT32(NOTIFICATION_RUNTIME_MAX_CHANNELS,registry.size());}
void test_begin_empty_multiple_disabled_rebegin_and_no_sink_calls()
{NotificationRegistry empty;NotificationRuntime emptyRuntime(empty);assertResult(NotificationRuntimeResult::SUCCESS,emptyRuntime.begin());TEST_ASSERT_TRUE(emptyRuntime.isInitialized());assertResult(NotificationRuntimeResult::NO_CHANGE,emptyRuntime.update(0U));NotificationRegistry registry;FakeNotificationSink one,two;registry.registerChannel(descriptor(1U),one);registry.registerChannel(descriptor(2U,false),two);NotificationRuntime runtime(registry);assertResult(NotificationRuntimeResult::SUCCESS,runtime.begin());TEST_ASSERT_TRUE(registry.isLocked());TEST_ASSERT_TRUE(runtime.state(1U)->isValid());TEST_ASSERT_TRUE(runtime.state(2U)->isValid());assertResult(NotificationRuntimeResult::CHANNEL_DISABLED,runtime.state(2U)->lastResult());TEST_ASSERT_EQUAL_UINT32(0U,one.sendCalls+one.updateCalls+one.cancelCalls+two.sendCalls+two.updateCalls+two.cancelCalls);assertResult(NotificationRuntimeResult::SUCCESS,runtime.begin());}
void test_send_validation_order_forwarding_and_independence()
{NotificationRegistry registry;FakeNotificationSink one,two,disabled;registry.registerChannel(descriptor(1U),one);registry.registerChannel(descriptor(2U),two);registry.registerChannel(descriptor(3U,false),disabled);NotificationRuntime runtime(registry);assertResult(NotificationRuntimeResult::NOT_INITIALIZED,runtime.send(message(),100U));runtime.begin();assertResult(NotificationRuntimeResult::INVALID_NOTIFICATION,runtime.send(NotificationMessage{},100U));assertResult(NotificationRuntimeResult::EXPIRED,runtime.send(message(),150U));assertResult(NotificationRuntimeResult::CHANNEL_NOT_FOUND,runtime.send(message(1U,9U),100U));assertResult(NotificationRuntimeResult::CHANNEL_DISABLED,runtime.send(message(1U,3U),100U));one.sendResult=NotificationSinkResult::ACCEPTED;NotificationMessage sent=message();assertResult(NotificationRuntimeResult::ACCEPTED,runtime.send(sent,100U));TEST_ASSERT_TRUE(runtime.isBusy(1U));TEST_ASSERT_EQUAL_UINT32(10U,runtime.state(1U)->activeNotificationId());TEST_ASSERT_EQUAL_PTR(sent.payload(),one.lastPayload);TEST_ASSERT_EQUAL_PTR(sent.target(),one.lastTarget);TEST_ASSERT_EQUAL_PTR(registry.findDescriptor(1U),one.lastDescriptor);assertResult(NotificationRuntimeResult::CHANNEL_BUSY,runtime.send(sent,100U));TEST_ASSERT_EQUAL_UINT32(1U,one.sendCalls);two.sendResult=NotificationSinkResult::SUCCESS;assertResult(NotificationRuntimeResult::SUCCESS,runtime.send(message(20U,2U),100U));TEST_ASSERT_EQUAL_UINT32(1U,two.sendCalls);TEST_ASSERT_EQUAL_UINT32(0U,disabled.sendCalls);}
static void assert_send_mapping(NotificationSinkResult sinkResult,NotificationRuntimeResult returned,NotificationRuntimeResult stored,bool busy)
{NotificationRegistry registry;FakeNotificationSink sink;sink.sendResult=sinkResult;registry.registerChannel(descriptor(1U),sink);NotificationRuntime runtime(registry);runtime.begin();assertResult(returned,runtime.send(message(),100U));assertResult(stored,runtime.state(1U)->lastResult());TEST_ASSERT_EQUAL(busy,runtime.isBusy(1U));TEST_ASSERT_EQUAL_UINT32(busy?10U:0U,runtime.state(1U)->activeNotificationId());TEST_ASSERT_EQUAL_UINT32(1U,sink.sendCalls);}
void test_send_result_mapping_and_fail_closed()
{assert_send_mapping(NotificationSinkResult::SUCCESS,NotificationRuntimeResult::SUCCESS,NotificationRuntimeResult::SUCCESS,false);assert_send_mapping(NotificationSinkResult::ACCEPTED,NotificationRuntimeResult::ACCEPTED,NotificationRuntimeResult::ACCEPTED,true);assert_send_mapping(NotificationSinkResult::IN_PROGRESS,NotificationRuntimeResult::ACCEPTED,NotificationRuntimeResult::IN_PROGRESS,true);assert_send_mapping(NotificationSinkResult::RETRY_LATER,NotificationRuntimeResult::RETRY_LATER,NotificationRuntimeResult::RETRY_LATER,false);assert_send_mapping(NotificationSinkResult::REJECTED,NotificationRuntimeResult::SINK_REJECTED,NotificationRuntimeResult::SINK_REJECTED,false);assert_send_mapping(NotificationSinkResult::CANCELLED,NotificationRuntimeResult::CANCELLED,NotificationRuntimeResult::CANCELLED,false);assert_send_mapping(NotificationSinkResult::FAILED,NotificationRuntimeResult::SINK_FAILED,NotificationRuntimeResult::SINK_FAILED,false);assert_send_mapping(static_cast<NotificationSinkResult>(255U),NotificationRuntimeResult::INTERNAL_ERROR,NotificationRuntimeResult::INTERNAL_ERROR,false);}
static void assert_update_mapping(NotificationSinkResult sinkResult,NotificationRuntimeResult expected,bool busy)
{NotificationRegistry registry;FakeNotificationSink sink;sink.sendResult=NotificationSinkResult::ACCEPTED;sink.updateResult=sinkResult;registry.registerChannel(descriptor(1U),sink);NotificationRuntime runtime(registry);runtime.begin();runtime.send(message(),100U);assertResult(expected,runtime.update(999U));TEST_ASSERT_EQUAL(busy,runtime.isBusy(1U));TEST_ASSERT_EQUAL_UINT32(busy?10U:0U,runtime.state(1U)->activeNotificationId());TEST_ASSERT_EQUAL_UINT32(1U,sink.updateCalls);}
void test_update_mapping_terminal_nonterminal_and_fail_closed()
{assert_update_mapping(NotificationSinkResult::SUCCESS,NotificationRuntimeResult::SUCCESS,false);assert_update_mapping(NotificationSinkResult::ACCEPTED,NotificationRuntimeResult::ACCEPTED,true);assert_update_mapping(NotificationSinkResult::IN_PROGRESS,NotificationRuntimeResult::IN_PROGRESS,true);assert_update_mapping(NotificationSinkResult::RETRY_LATER,NotificationRuntimeResult::RETRY_LATER,true);assert_update_mapping(NotificationSinkResult::CANCELLED,NotificationRuntimeResult::CANCELLED,false);assert_update_mapping(NotificationSinkResult::REJECTED,NotificationRuntimeResult::SINK_REJECTED,false);assert_update_mapping(NotificationSinkResult::FAILED,NotificationRuntimeResult::SINK_FAILED,false);assert_update_mapping(static_cast<NotificationSinkResult>(254U),NotificationRuntimeResult::INTERNAL_ERROR,false);}
void test_update_only_busy_once_and_aggregation_priority()
{NotificationRegistry registry;FakeNotificationSink sinks[8];for(uint8_t i=0U;i<8U;++i){sinks[i].sendResult=NotificationSinkResult::ACCEPTED;registry.registerChannel(descriptor(static_cast<uint8_t>(i+1U)),sinks[i]);}NotificationRuntime runtime(registry);runtime.begin();assertResult(NotificationRuntimeResult::NO_CHANGE,runtime.update(0U));for(uint8_t i=0U;i<8U;++i)runtime.send(message(static_cast<uint32_t>(i+1U),static_cast<uint8_t>(i+1U)),100U);sinks[0].updateResult=NotificationSinkResult::RETRY_LATER;sinks[1].updateResult=NotificationSinkResult::ACCEPTED;sinks[2].updateResult=NotificationSinkResult::IN_PROGRESS;sinks[3].updateResult=NotificationSinkResult::SUCCESS;sinks[4].updateResult=NotificationSinkResult::CANCELLED;sinks[5].updateResult=NotificationSinkResult::REJECTED;sinks[6].updateResult=NotificationSinkResult::FAILED;sinks[7].updateResult=static_cast<NotificationSinkResult>(99U);assertResult(NotificationRuntimeResult::INTERNAL_ERROR,runtime.update(1000U));for(uint8_t i=0U;i<8U;++i)TEST_ASSERT_EQUAL_UINT32(1U,sinks[i].updateCalls);TEST_ASSERT_TRUE(runtime.isBusy(1U));TEST_ASSERT_TRUE(runtime.isBusy(2U));TEST_ASSERT_TRUE(runtime.isBusy(3U));TEST_ASSERT_FALSE(runtime.isBusy(4U));TEST_ASSERT_FALSE(runtime.isBusy(8U));}
static void assert_cancel_mapping(NotificationSinkResult sinkResult,NotificationRuntimeResult expected,bool busy)
{NotificationRegistry registry;FakeNotificationSink sink;sink.sendResult=NotificationSinkResult::ACCEPTED;sink.cancelResult=sinkResult;registry.registerChannel(descriptor(1U),sink);NotificationRuntime runtime(registry);runtime.begin();runtime.send(message(),100U);assertResult(expected,runtime.cancel(1U));TEST_ASSERT_EQUAL(busy,runtime.isBusy(1U));TEST_ASSERT_EQUAL_UINT32(busy?10U:0U,runtime.state(1U)->activeNotificationId());TEST_ASSERT_EQUAL_UINT32(1U,sink.cancelCalls);}
void test_cancel_validation_mapping_and_fail_closed()
{NotificationRegistry registry;FakeNotificationSink sink,disabled;registry.registerChannel(descriptor(1U),sink);registry.registerChannel(descriptor(2U,false),disabled);NotificationRuntime runtime(registry);assertResult(NotificationRuntimeResult::NOT_INITIALIZED,runtime.cancel(1U));runtime.begin();assertResult(NotificationRuntimeResult::CHANNEL_NOT_FOUND,runtime.cancel(9U));assertResult(NotificationRuntimeResult::CHANNEL_DISABLED,runtime.cancel(2U));assertResult(NotificationRuntimeResult::INVALID_ARGUMENT,runtime.cancel(1U));assert_cancel_mapping(NotificationSinkResult::SUCCESS,NotificationRuntimeResult::SUCCESS,false);assert_cancel_mapping(NotificationSinkResult::IN_PROGRESS,NotificationRuntimeResult::IN_PROGRESS,true);assert_cancel_mapping(NotificationSinkResult::RETRY_LATER,NotificationRuntimeResult::RETRY_LATER,true);assert_cancel_mapping(NotificationSinkResult::CANCELLED,NotificationRuntimeResult::CANCELLED,false);assert_cancel_mapping(NotificationSinkResult::REJECTED,NotificationRuntimeResult::SINK_REJECTED,false);assert_cancel_mapping(NotificationSinkResult::FAILED,NotificationRuntimeResult::SINK_FAILED,false);assert_cancel_mapping(NotificationSinkResult::ACCEPTED,NotificationRuntimeResult::INTERNAL_ERROR,false);assert_cancel_mapping(static_cast<NotificationSinkResult>(255U),NotificationRuntimeResult::INTERNAL_ERROR,false);}
void test_rebegin_busy_state_lookup_and_multiple_instances()
{NotificationRegistry firstRegistry,secondRegistry;FakeNotificationSink firstSink,secondSink;firstSink.sendResult=NotificationSinkResult::ACCEPTED;firstRegistry.registerChannel(descriptor(1U),firstSink);secondRegistry.registerChannel(descriptor(2U),secondSink);NotificationRuntime first(firstRegistry),second(secondRegistry);TEST_ASSERT_NULL(first.state(1U));first.begin();second.begin();first.send(message(),100U);assertResult(NotificationRuntimeResult::CHANNEL_BUSY,first.begin());TEST_ASSERT_TRUE(first.isBusy(1U));TEST_ASSERT_FALSE(second.isBusy(2U));TEST_ASSERT_NULL(second.state(1U));firstSink.cancelResult=NotificationSinkResult::SUCCESS;first.cancel(1U);assertResult(NotificationRuntimeResult::SUCCESS,first.begin());TEST_ASSERT_FALSE(first.isBusy(1U));}

static_assert(std::is_base_of<NotificationSink,FakeNotificationSink>::value,"sink contract");
void setup()
{UNITY_BEGIN();RUN_TEST(test_message_default_validation_bounds_and_views);RUN_TEST(test_message_expiration_threshold_and_wraparound);RUN_TEST(test_descriptor_and_enum_validation);RUN_TEST(test_registry_registration_lookup_capacity_lock_and_atomicity);RUN_TEST(test_begin_empty_multiple_disabled_rebegin_and_no_sink_calls);RUN_TEST(test_send_validation_order_forwarding_and_independence);RUN_TEST(test_send_result_mapping_and_fail_closed);RUN_TEST(test_update_mapping_terminal_nonterminal_and_fail_closed);RUN_TEST(test_update_only_busy_once_and_aggregation_priority);RUN_TEST(test_cancel_validation_mapping_and_fail_closed);RUN_TEST(test_rebegin_busy_state_lookup_and_multiple_instances);UNITY_END();}
void loop(){}
