#include <unity.h>
#include <type_traits>
#include <string.h>
#include <CommandToEventAdapter.h>
#include <EventQueue.h>
#include <EventToNotificationAdapter.h>
#include <NodeToEventAdapter.h>
#include <NodeRuntime.h>

class FakeFormatter final:public EventNotificationFormatter
{public:EventNotificationFormatResult result=EventNotificationFormatResult::SUCCESS;size_t calls=0U;const Event* lastEvent=nullptr;uint8_t* output=nullptr;size_t capacity=0U;size_t configuredLength=3U;uint8_t bytes[NOTIFICATION_RUNTIME_MAX_PAYLOAD_LENGTH]={0x41U,0U,0x42U};EventNotificationFormatResult format(const Event& e,uint8_t* out,size_t cap,size_t& length)override{++calls;lastEvent=&e;output=out;capacity=cap;length=configuredLength;if(result==EventNotificationFormatResult::SUCCESS&&configuredLength<=cap)memcpy(out,bytes,configuredLength);return result;}};
class FakeNotificationSink final:public NotificationSink
{public:NotificationSinkResult sendResult=NotificationSinkResult::SUCCESS;size_t sendCalls=0U,updateCalls=0U,cancelCalls=0U;NotificationId id=0U;NotificationChannelId channel=0U;const char* target=nullptr;size_t targetLength=0U;const uint8_t* payload=nullptr;size_t payloadLength=0U;NotificationSinkResult sendNotification(const NotificationMessage& m,const NotificationChannelDescriptor& d)override{++sendCalls;id=m.notificationId();channel=d.channelId();target=m.target();targetLength=m.targetLength();payload=m.payload();payloadLength=m.payloadLength();return sendResult;}NotificationSinkResult updateNotificationSend(NotificationChannelId)override{++updateCalls;return NotificationSinkResult::SUCCESS;}NotificationSinkResult cancelNotificationSend(NotificationChannelId)override{++cancelCalls;return NotificationSinkResult::SUCCESS;}};
class FakeEventSink final:public EventSink
{public:EventPublishResult result=EventPublishResult::SUCCESS;size_t calls=0U;Event event{};EventPublishResult publish(const Event& e)override{++calls;event=e;return result;}};
class FakeNodeInboundSink final:public NodeMessageSink{public:NodeMessageSinkResult onNodeMessage(const NodeInboundMessage&)override{return NodeMessageSinkResult::ACCEPTED;}};
class FakeNodeOutboundSink final:public NodeOutboundSink{public:NodeOutboundSinkResult sendToNode(NodeMessageId,const NodeDescriptor&,const uint8_t*,size_t)override{return NodeOutboundSinkResult::SUCCESS;}NodeOutboundSinkResult updateNodeSend(NodeId)override{return NodeOutboundSinkResult::SUCCESS;}NodeOutboundSinkResult cancelNodeSend(NodeId)override{return NodeOutboundSinkResult::SUCCESS;}};
class FakeIds final:public RuntimeIntegrationEventIdProvider{public:EventId next=1U;size_t calls=0U;EventId nextEventId()override{++calls;EventId value=next++;if(next==0U)next=1U;return value;}};
class EventToNotificationAdapterTestAccess{public:static void setNext(EventToNotificationAdapter& a,NotificationId id){a.nextId_=id;}static void saturate(EventToNotificationAdapter& a){a.forwarded_=UINT32_MAX;a.ignored_=UINT32_MAX;a.failed_=UINT32_MAX;}static RuntimeIntegrationResult map(NotificationRuntimeResult r){return EventToNotificationAdapter::mapRuntimeResult(r);}};
class NodeToEventAdapterTestAccess{public:static void saturate(NodeToEventAdapter& a){a.forwarded_=UINT32_MAX;a.ignored_=UINT32_MAX;a.failed_=UINT32_MAX;}};
class CommandToEventAdapterTestAccess{public:static void saturate(CommandToEventAdapter& a){a.forwarded_=UINT32_MAX;a.ignored_=UINT32_MAX;a.failed_=UINT32_MAX;}};

static void assertIntegration(RuntimeIntegrationResult e,RuntimeIntegrationResult a){TEST_ASSERT_EQUAL_UINT8(static_cast<uint8_t>(e),static_cast<uint8_t>(a));}
static Event makeEvent(EventType type=EventType::NODE_OFFLINE,EventSeverity severity=EventSeverity::ERROR,EventId id=1U){Event e;e.id=id;e.type=type;e.severity=severity;e.sourceType=EventSourceType::NODE;e.sourceId=7U;e.timestampMs=100U;return e;}
static CommandResult commandResult(ExecutionStatus status,CommandErrorCode error){CommandResult r;r.commandId=31U;r.requestId=41U;if(status==ExecutionStatus::REJECTED)r.transitionTo(status,10U,error);else if(status==ExecutionStatus::SUCCESS){r.transitionTo(ExecutionStatus::VALIDATING,1U);r.transitionTo(ExecutionStatus::ACCEPTED,2U);r.transitionTo(ExecutionStatus::EXECUTING,3U);r.transitionTo(status,4U,error);}else if(status==ExecutionStatus::FAILED){r.transitionTo(ExecutionStatus::VALIDATING,1U);r.transitionTo(ExecutionStatus::ACCEPTED,2U);r.transitionTo(ExecutionStatus::EXECUTING,3U);r.transitionTo(status,4U,error);}return r;}
static NodeAddress nodeAddress(const char* text){NodeAddress a;TEST_ASSERT_TRUE(a.set(text));return a;}

struct NotificationFixture
{FakeNotificationSink sink;NotificationRegistry channels;NotificationRuntime runtime;FakeFormatter formatter;EventNotificationRegistry mappings;EventToNotificationAdapter adapter;NotificationFixture(bool beginRuntime=true):sink(),channels(),runtime(channels),formatter(),mappings(),adapter(mappings,formatter,runtime){channels.registerChannel(NotificationChannelDescriptor::create(1U,NotificationChannelType::GENERIC,true),sink);if(beginRuntime)runtime.begin();const char target[]={'a','p','p'};mappings.registerMapping(EventNotificationMapping::create(EventType::NODE_OFFLINE,EventSeverity::WARNING,1U,NotificationPriority::HIGH_PRIORITY,100U,target,sizeof(target),true));adapter.begin();}};

void test_common_mapping_models_and_validation()
{const char target[]={'x','y'};TEST_ASSERT_FALSE(EventNotificationMapping{}.isValid());TEST_ASSERT_FALSE(EventNotificationMapping::create(EventType::NONE,EventSeverity::INFO,1U,NotificationPriority::NORMAL,1U,target,2U,true).isValid());TEST_ASSERT_FALSE(EventNotificationMapping::create(EventType::NODE_OFFLINE,EventSeverity::COUNT,1U,NotificationPriority::NORMAL,1U,target,2U,true).isValid());TEST_ASSERT_FALSE(EventNotificationMapping::create(EventType::NODE_OFFLINE,EventSeverity::INFO,0U,NotificationPriority::NORMAL,1U,target,2U,true).isValid());TEST_ASSERT_FALSE(EventNotificationMapping::create(EventType::NODE_OFFLINE,EventSeverity::INFO,1U,NotificationPriority::COUNT,1U,target,2U,true).isValid());TEST_ASSERT_FALSE(EventNotificationMapping::create(EventType::NODE_OFFLINE,EventSeverity::INFO,1U,NotificationPriority::NORMAL,0U,target,2U,true).isValid());TEST_ASSERT_FALSE(EventNotificationMapping::create(EventType::NODE_OFFLINE,EventSeverity::INFO,1U,NotificationPriority::NORMAL,1U,nullptr,2U,true).isValid());TEST_ASSERT_TRUE(EventNotificationMapping::create(EventType::NODE_OFFLINE,EventSeverity::INFO,1U,NotificationPriority::NORMAL,1U,target,2U,false).isValid());TEST_ASSERT_FALSE(NodeEventMapping{}.isValid());TEST_ASSERT_TRUE(NodeEventMapping::create(NodeEventSignal::ONLINE,EventType::NODE_ONLINE,EventSeverity::NOTICE,true).isValid());TEST_ASSERT_FALSE(CommandEventMapping{}.isValid());TEST_ASSERT_TRUE(CommandEventMapping::create(ExecutionStatus::FAILED,CommandErrorCode::HARDWARE_FAILURE,EventType::COMMAND_FAILED,EventSeverity::ERROR,true).isValid());}
void test_registries_atomic_duplicate_lock_and_target_ownership()
{char target[]={'a','b'};EventNotificationRegistry e;EventNotificationMapping m=EventNotificationMapping::create(EventType::NODE_OFFLINE,EventSeverity::WARNING,1U,NotificationPriority::NORMAL,10U,target,2U,true);assertIntegration(RuntimeIntegrationResult::SUCCESS,e.registerMapping(m));target[0]='z';TEST_ASSERT_EQUAL_UINT8(static_cast<uint8_t>('a'),static_cast<uint8_t>(e.find(EventType::NODE_OFFLINE)->target()[0]));assertIntegration(RuntimeIntegrationResult::DUPLICATE_MAPPING,e.registerMapping(m));TEST_ASSERT_EQUAL_UINT32(1U,e.size());e.lock();assertIntegration(RuntimeIntegrationResult::REGISTRY_LOCKED,e.registerMapping(EventNotificationMapping{}));NodeEventRegistry n;assertIntegration(RuntimeIntegrationResult::INVALID_INPUT,n.registerMapping(NodeEventMapping{}));assertIntegration(RuntimeIntegrationResult::SUCCESS,n.registerMapping(NodeEventMapping::create(NodeEventSignal::OFFLINE,EventType::NODE_OFFLINE,EventSeverity::ERROR,true)));assertIntegration(RuntimeIntegrationResult::DUPLICATE_MAPPING,n.registerMapping(NodeEventMapping::create(NodeEventSignal::OFFLINE,EventType::NODE_OFFLINE,EventSeverity::ERROR,true)));CommandEventRegistry c;CommandEventMapping cm=CommandEventMapping::create(ExecutionStatus::SUCCESS,CommandErrorCode::NONE,EventType::COMMAND_EXECUTED,EventSeverity::INFO,true);assertIntegration(RuntimeIntegrationResult::SUCCESS,c.registerMapping(cm));c.lock();assertIntegration(RuntimeIntegrationResult::REGISTRY_LOCKED,c.registerMapping(cm));}
void test_event_notification_filter_formatter_id_and_payload()
{NotificationFixture f;Event invalid;assertIntegration(RuntimeIntegrationResult::INVALID_INPUT,f.adapter.onEvent(invalid,100U));TEST_ASSERT_EQUAL_UINT32(1U,f.adapter.nextNotificationId());assertIntegration(RuntimeIntegrationResult::IGNORED,f.adapter.onEvent(makeEvent(EventType::NODE_ONLINE),100U));assertIntegration(RuntimeIntegrationResult::FILTERED,f.adapter.onEvent(makeEvent(EventType::NODE_OFFLINE,EventSeverity::NOTICE),100U));TEST_ASSERT_EQUAL_UINT32(0U,f.formatter.calls);f.formatter.result=EventNotificationFormatResult::NO_CONTENT;assertIntegration(RuntimeIntegrationResult::IGNORED,f.adapter.onEvent(makeEvent(),100U));TEST_ASSERT_EQUAL_UINT32(1U,f.adapter.nextNotificationId());f.formatter.result=EventNotificationFormatResult::SUCCESS;assertIntegration(RuntimeIntegrationResult::SUCCESS,f.adapter.onEvent(makeEvent(),100U));TEST_ASSERT_EQUAL_UINT32(1U,f.sink.sendCalls);TEST_ASSERT_EQUAL_UINT32(1U,f.sink.id);TEST_ASSERT_EQUAL_UINT8_ARRAY(f.formatter.bytes,f.sink.payload,3U);TEST_ASSERT_EQUAL_UINT32(NOTIFICATION_RUNTIME_MAX_PAYLOAD_LENGTH,f.formatter.capacity);TEST_ASSERT_EQUAL_UINT32(2U,f.adapter.nextNotificationId());}
void test_event_notification_formatter_fail_closed_and_runtime_mapping()
{NotificationFixture f;f.formatter.result=EventNotificationFormatResult::BUFFER_TOO_SMALL;assertIntegration(RuntimeIntegrationResult::FAILED,f.adapter.onEvent(makeEvent(),100U));f.formatter.result=EventNotificationFormatResult::INVALID_EVENT;assertIntegration(RuntimeIntegrationResult::INVALID_INPUT,f.adapter.onEvent(makeEvent(),100U));f.formatter.result=static_cast<EventNotificationFormatResult>(255U);assertIntegration(RuntimeIntegrationResult::INTERNAL_ERROR,f.adapter.onEvent(makeEvent(),100U));TEST_ASSERT_EQUAL_UINT32(0U,f.sink.sendCalls);TEST_ASSERT_EQUAL_UINT32(1U,f.adapter.nextNotificationId());TEST_ASSERT_EQUAL_UINT8(static_cast<uint8_t>(RuntimeIntegrationResult::RETRY_LATER),static_cast<uint8_t>(EventToNotificationAdapterTestAccess::map(NotificationRuntimeResult::CHANNEL_BUSY)));TEST_ASSERT_EQUAL_UINT8(static_cast<uint8_t>(RuntimeIntegrationResult::FAILED),static_cast<uint8_t>(EventToNotificationAdapterTestAccess::map(NotificationRuntimeResult::CHANNEL_NOT_FOUND)));TEST_ASSERT_EQUAL_UINT8(static_cast<uint8_t>(RuntimeIntegrationResult::INTERNAL_ERROR),static_cast<uint8_t>(EventToNotificationAdapterTestAccess::map(static_cast<NotificationRuntimeResult>(255U))));}
void test_notification_results_id_wrap_busy_and_saturation()
{NotificationFixture f;f.sink.sendResult=NotificationSinkResult::ACCEPTED;EventToNotificationAdapterTestAccess::setNext(f.adapter,UINT32_MAX);assertIntegration(RuntimeIntegrationResult::ACCEPTED,f.adapter.onEvent(makeEvent(),100U));TEST_ASSERT_EQUAL_UINT32(UINT32_MAX,f.sink.id);TEST_ASSERT_EQUAL_UINT32(1U,f.adapter.nextNotificationId());assertIntegration(RuntimeIntegrationResult::RETRY_LATER,f.adapter.onEvent(makeEvent(),100U));TEST_ASSERT_EQUAL_UINT32(1U,f.sink.sendCalls);TEST_ASSERT_EQUAL_UINT32(2U,f.adapter.failedCount());EventToNotificationAdapterTestAccess::saturate(f.adapter);f.adapter.onEvent(makeEvent(EventType::NODE_ONLINE),100U);TEST_ASSERT_EQUAL_UINT32(UINT32_MAX,f.adapter.forwardedCount());TEST_ASSERT_EQUAL_UINT32(UINT32_MAX,f.adapter.ignoredCount());TEST_ASSERT_EQUAL_UINT32(UINT32_MAX,f.adapter.failedCount());}
void test_node_adapter_real_state_transitions_results_and_no_duplicates()
{NodeRuntimeRegistry nodes;nodes.registerNode(NodeDescriptor::create(7U,NodeType::CUSTOM,nodeAddress("n/7"),50U,true));FakeNodeInboundSink inbound;FakeNodeOutboundSink outbound;NodeRuntime runtime(nodes,inbound,outbound);runtime.begin(0U);NodeRuntimeState before=*runtime.state(7U);uint8_t p[]={1U};runtime.handleInbound(NodeInboundMessage::create(1U,7U,nodeAddress("n/7"),p,1U),10U);NodeRuntimeState online=*runtime.state(7U);FakeEventSink events;FakeIds ids;NodeEventRegistry mappings;mappings.registerMapping(NodeEventMapping::create(NodeEventSignal::ONLINE,EventType::NODE_ONLINE,EventSeverity::NOTICE,true));mappings.registerMapping(NodeEventMapping::create(NodeEventSignal::OFFLINE,EventType::NODE_OFFLINE,EventSeverity::ERROR,true));mappings.registerMapping(NodeEventMapping::create(NodeEventSignal::SINK_REJECTED,EventType::NODE_HEALTH_CHANGED,EventSeverity::ERROR,true));NodeToEventAdapter adapter(mappings,events,ids);assertIntegration(RuntimeIntegrationResult::NOT_INITIALIZED,adapter.onNodeStateChanged(before,online,10U));adapter.begin();assertIntegration(RuntimeIntegrationResult::SUCCESS,adapter.onNodeStateChanged(before,online,10U));TEST_ASSERT_EQUAL_UINT16(7U,events.event.sourceId);TEST_ASSERT_EQUAL_UINT16(static_cast<uint16_t>(EventType::NODE_ONLINE),static_cast<uint16_t>(events.event.type));assertIntegration(RuntimeIntegrationResult::NO_CHANGE,adapter.onNodeStateChanged(online,online,11U));TEST_ASSERT_EQUAL_UINT32(1U,events.calls);runtime.update(60U);NodeRuntimeState offline=*runtime.state(7U);assertIntegration(RuntimeIntegrationResult::SUCCESS,adapter.onNodeStateChanged(online,offline,60U));assertIntegration(RuntimeIntegrationResult::SUCCESS,adapter.onNodeResult(7U,NodeRuntimeResult::SINK_REJECTED,61U));assertIntegration(RuntimeIntegrationResult::INVALID_INPUT,adapter.onNodeResult(0U,NodeRuntimeResult::SUCCESS,62U));assertIntegration(RuntimeIntegrationResult::INVALID_INPUT,adapter.onNodeResult(7U,static_cast<NodeRuntimeResult>(255U),62U));}
void test_node_publish_mapping_disabled_queue_full_and_saturation()
{NodeEventRegistry mappings;mappings.registerMapping(NodeEventMapping::create(NodeEventSignal::SEND_SUCCESS,EventType::NODE_HEALTH_CHANGED,EventSeverity::INFO,true));mappings.registerMapping(NodeEventMapping::create(NodeEventSignal::INTERNAL_ERROR,EventType::NODE_HEALTH_CHANGED,EventSeverity::CRITICAL,false));FakeEventSink sink;FakeIds ids;NodeToEventAdapter adapter(mappings,sink,ids);adapter.begin();assertIntegration(RuntimeIntegrationResult::SUCCESS,adapter.onNodeResult(2U,NodeRuntimeResult::SUCCESS,1U));sink.result=EventPublishResult::QUEUE_FULL;assertIntegration(RuntimeIntegrationResult::RETRY_LATER,adapter.onNodeResult(2U,NodeRuntimeResult::SUCCESS,2U));assertIntegration(RuntimeIntegrationResult::MAPPING_DISABLED,adapter.onNodeResult(2U,NodeRuntimeResult::INTERNAL_ERROR,3U));assertIntegration(RuntimeIntegrationResult::IGNORED,adapter.onNodeResult(2U,NodeRuntimeResult::ACCEPTED,4U));TEST_ASSERT_EQUAL_UINT32(2U,sink.calls);NodeToEventAdapterTestAccess::saturate(adapter);adapter.onNodeResult(2U,NodeRuntimeResult::SUCCESS,5U);TEST_ASSERT_EQUAL_UINT32(UINT32_MAX,adapter.forwardedCount());}
void test_command_adapter_mapping_sensitive_policy_and_results()
{CommandEventRegistry mappings;mappings.registerMapping(CommandEventMapping::create(ExecutionStatus::SUCCESS,CommandErrorCode::NONE,EventType::COMMAND_EXECUTED,EventSeverity::INFO,true));mappings.registerMapping(CommandEventMapping::create(ExecutionStatus::REJECTED,CommandErrorCode::UNAUTHORIZED,EventType::COMMAND_REJECTED,EventSeverity::ERROR,true));mappings.registerMapping(CommandEventMapping::create(ExecutionStatus::FAILED,CommandErrorCode::HARDWARE_FAILURE,EventType::COMMAND_FAILED,EventSeverity::CRITICAL,false));FakeEventSink sink;FakeIds ids;CommandToEventAdapter adapter(mappings,sink,ids);assertIntegration(RuntimeIntegrationResult::NOT_INITIALIZED,adapter.onCommandResult(commandResult(ExecutionStatus::SUCCESS,CommandErrorCode::NONE),10U));adapter.begin();assertIntegration(RuntimeIntegrationResult::SUCCESS,adapter.onCommandResult(commandResult(ExecutionStatus::SUCCESS,CommandErrorCode::NONE),10U));TEST_ASSERT_EQUAL_UINT32(31U,sink.event.payload.value1);TEST_ASSERT_EQUAL_UINT32(41U,sink.event.correlationId);TEST_ASSERT_EQUAL_STRING("",sink.event.message);assertIntegration(RuntimeIntegrationResult::SUCCESS,adapter.onCommandResult(commandResult(ExecutionStatus::REJECTED,CommandErrorCode::UNAUTHORIZED),11U));assertIntegration(RuntimeIntegrationResult::MAPPING_DISABLED,adapter.onCommandResult(commandResult(ExecutionStatus::FAILED,CommandErrorCode::HARDWARE_FAILURE),12U));CommandResult invalid;assertIntegration(RuntimeIntegrationResult::INVALID_INPUT,adapter.onCommandResult(invalid,13U));sink.result=EventPublishResult::QUEUE_FULL;assertIntegration(RuntimeIntegrationResult::RETRY_LATER,adapter.onCommandResult(commandResult(ExecutionStatus::SUCCESS,CommandErrorCode::NONE),14U));TEST_ASSERT_EQUAL_UINT32(3U,sink.calls);}
void test_command_unknown_mapping_duplicate_publish_and_saturation()
{CommandEventRegistry mappings;mappings.registerMapping(CommandEventMapping::create(ExecutionStatus::SUCCESS,CommandErrorCode::NONE,EventType::COMMAND_EXECUTED,EventSeverity::INFO,true));FakeEventSink sink;FakeIds ids;CommandToEventAdapter adapter(mappings,sink,ids);adapter.begin();assertIntegration(RuntimeIntegrationResult::IGNORED,adapter.onCommandResult(commandResult(ExecutionStatus::REJECTED,CommandErrorCode::INVALID_COMMAND),1U));sink.result=EventPublishResult::DUPLICATE_EVENT;assertIntegration(RuntimeIntegrationResult::REJECTED,adapter.onCommandResult(commandResult(ExecutionStatus::SUCCESS,CommandErrorCode::NONE),2U));CommandToEventAdapterTestAccess::saturate(adapter);adapter.onCommandResult(commandResult(ExecutionStatus::SUCCESS,CommandErrorCode::NONE),3U);TEST_ASSERT_EQUAL_UINT32(UINT32_MAX,adapter.forwardedCount());TEST_ASSERT_EQUAL_UINT32(UINT32_MAX,adapter.ignoredCount());TEST_ASSERT_EQUAL_UINT32(UINT32_MAX,adapter.failedCount());}
void test_integration_node_to_event_to_notification()
{EventQueue queue;FakeIds ids;NodeEventRegistry nodeMappings;nodeMappings.registerMapping(NodeEventMapping::create(NodeEventSignal::OFFLINE,EventType::NODE_OFFLINE,EventSeverity::ERROR,true));NodeToEventAdapter node(nodeMappings,queue,ids);node.begin();NotificationFixture notification;assertIntegration(RuntimeIntegrationResult::SUCCESS,node.onNodeResult(7U,NodeRuntimeResult::TIMEOUT,100U));TEST_ASSERT_NOT_NULL(queue.peek());assertIntegration(RuntimeIntegrationResult::SUCCESS,notification.adapter.onEvent(*queue.peek(),100U));TEST_ASSERT_EQUAL_UINT32(1U,notification.sink.sendCalls);}
void test_integration_command_failure_filter_disabled_and_busy()
{EventQueue queue;FakeIds ids;CommandEventRegistry commands;commands.registerMapping(CommandEventMapping::create(ExecutionStatus::FAILED,CommandErrorCode::HARDWARE_FAILURE,EventType::NODE_OFFLINE,EventSeverity::ERROR,true));CommandToEventAdapter command(commands,queue,ids);command.begin();NotificationFixture notification;notification.sink.sendResult=NotificationSinkResult::ACCEPTED;assertIntegration(RuntimeIntegrationResult::SUCCESS,command.onCommandResult(commandResult(ExecutionStatus::FAILED,CommandErrorCode::HARDWARE_FAILURE),100U));assertIntegration(RuntimeIntegrationResult::ACCEPTED,notification.adapter.onEvent(*queue.peek(),100U));assertIntegration(RuntimeIntegrationResult::RETRY_LATER,notification.adapter.onEvent(*queue.peek(),100U));TEST_ASSERT_EQUAL_UINT32(1U,notification.sink.sendCalls);}

static_assert(std::is_base_of<EventHandler,EventToNotificationAdapter>::value,"event handler integration");
void setup(){UNITY_BEGIN();RUN_TEST(test_common_mapping_models_and_validation);RUN_TEST(test_registries_atomic_duplicate_lock_and_target_ownership);RUN_TEST(test_event_notification_filter_formatter_id_and_payload);RUN_TEST(test_event_notification_formatter_fail_closed_and_runtime_mapping);RUN_TEST(test_notification_results_id_wrap_busy_and_saturation);RUN_TEST(test_node_adapter_real_state_transitions_results_and_no_duplicates);RUN_TEST(test_node_publish_mapping_disabled_queue_full_and_saturation);RUN_TEST(test_command_adapter_mapping_sensitive_policy_and_results);RUN_TEST(test_command_unknown_mapping_duplicate_publish_and_saturation);RUN_TEST(test_integration_node_to_event_to_notification);RUN_TEST(test_integration_command_failure_filter_disabled_and_busy);UNITY_END();}void loop(){}
