#include "ScheduleManager.h"
#include <string.h>
namespace { constexpr size_t INVALID_INDEX_VALUE=SCHEDULE_MANAGER_CAPACITY; }
ScheduleManager::ScheduleManager():schedules_{},count_(0){}void ScheduleManager::clear(){for(size_t i=0;i<SCHEDULE_MANAGER_CAPACITY;++i)schedules_[i]=Schedule{};count_=0;}
AutomationModelResult ScheduleManager::add(const Schedule& v){if(!v.isValid())return AutomationModelResult::INVALID_MODEL;if(isFull())return AutomationModelResult::CAPACITY_FULL;if(contains(v.id))return AutomationModelResult::DUPLICATE_ID;if(findByName(v.name))return AutomationModelResult::DUPLICATE_NAME;schedules_[count_++]=v;return AutomationModelResult::SUCCESS;}
AutomationModelResult ScheduleManager::update(const Schedule& v){if(!v.isValid())return AutomationModelResult::INVALID_MODEL;size_t i=findIndexById(v.id);if(i==INVALID_INDEX_VALUE)return AutomationModelResult::NOT_FOUND;if(nameBelongsToAnother(v.name,v.id))return AutomationModelResult::DUPLICATE_NAME;schedules_[i]=v;return AutomationModelResult::SUCCESS;}
AutomationModelResult ScheduleManager::remove(ScheduleId id){if(id==INVALID_SCHEDULE_ID)return AutomationModelResult::INVALID_ID;size_t i=findIndexById(id);if(i==INVALID_INDEX_VALUE)return AutomationModelResult::NOT_FOUND;for(size_t j=i+1U;j<count_;++j)schedules_[j-1U]=schedules_[j];--count_;schedules_[count_]=Schedule{};return AutomationModelResult::SUCCESS;}
size_t ScheduleManager::findIndexById(ScheduleId id)const{if(id==INVALID_SCHEDULE_ID)return INVALID_INDEX_VALUE;for(size_t i=0;i<count_;++i)if(schedules_[i].id==id)return i;return INVALID_INDEX_VALUE;}
const Schedule* ScheduleManager::findById(ScheduleId id)const{size_t i=findIndexById(id);return i==INVALID_INDEX_VALUE?nullptr:&schedules_[i];}const Schedule* ScheduleManager::findByName(const char* n)const{if(!n||n[0]=='\0')return nullptr;for(size_t i=0;i<count_;++i)if(strcmp(schedules_[i].name,n)==0)return &schedules_[i];return nullptr;}const Schedule* ScheduleManager::getAt(size_t i)const{return i<count_?&schedules_[i]:nullptr;}bool ScheduleManager::contains(ScheduleId id)const{return findIndexById(id)!=INVALID_INDEX_VALUE;}bool ScheduleManager::nameBelongsToAnother(const char* n,ScheduleId id)const{const Schedule* p=findByName(n);return p&&p->id!=id;}size_t ScheduleManager::size()const{return count_;}size_t ScheduleManager::capacity()const{return SCHEDULE_MANAGER_CAPACITY;}bool ScheduleManager::isFull()const{return count_>=SCHEDULE_MANAGER_CAPACITY;}bool ScheduleManager::isEmpty()const{return count_==0U;}
