#include <CompositeCommandExecutionGate.h>
#include <RuntimeAuthorizationPolicy.h>
#include <Arduino.h>
#include <string.h>
#include <unity.h>

static_assert(static_cast<uint8_t>(Permission::COUNT)<=64U,"Permission mask capacity exceeded");

namespace
{
Command makeCommand(CommandDomain domain=CommandDomain::OUT,CommandRisk risk=CommandRisk::ACTION)
{Command c;c.context.commandId=10U;c.context.request.requestId=20U;c.context.request.source=static_cast<CommandSource>(5U);c.context.risk=risk;c.domain=domain;c.domainIndex=1U;c.hasDomainIndex=true;c.operation=CommandOperation::ON;return c;}
Command makeQuery(){Command c=makeCommand(CommandDomain::OUT,CommandRisk::SAFE);c.operation=CommandOperation::NONE;c.queryType=CommandQueryType::ITEM_INFO;return c;}
User makeUser(UserId id=1U,RoleId roleId=1U,bool enabled=true){User u;u.id=id;u.roleId=roleId;u.enabled=enabled;return u;}
Role makeRole(RoleId id=1U,PermissionMask permissions=NO_PERMISSIONS,bool enabled=true){Role r;r.id=id;r.enabled=enabled;r.permissions=permissions;return r;}
class SubjectFake final:public AuthorizationSubjectProvider{public:AuthorizationCheckResult result=AuthorizationCheckResult::ALLOWED;AuthorizationSubject subject;mutable uint16_t calls=0;AuthorizationCheckResult resolve(const Command&,uint32_t,AuthorizationSubject& output)const override{++calls;if(result==AuthorizationCheckResult::ALLOWED)output=subject;return result;}};
class ModeFake final:public SystemModeProvider{public:mutable uint8_t calls=0;SystemMode getMode()const override{return SystemMode::NORMAL;}SystemModeCheckResult check(const Command&,uint32_t)const override{++calls;return SystemModeCheckResult::ALLOWED;}};
class SafetyFake final:public SafetyPolicy{public:mutable uint8_t calls=0;SafetyCheckResult check(const Command&,uint32_t)const override{++calls;return SafetyCheckResult::ALLOWED;}};
class TokenFake final:public ConfirmTokenProvider{public:mutable uint8_t checks=0;uint8_t consumes=0;ConfirmTokenCheckResult check(const Command&,uint32_t)const override{++checks;return ConfirmTokenCheckResult::NOT_REQUIRED;}ConfirmTokenCheckResult consume(const Command&,uint32_t)override{++consumes;return ConfirmTokenCheckResult::NOT_REQUIRED;}};
void setUserSubject(SubjectFake& p,UserId id=1U,bool authenticated=true){p.subject=AuthorizationSubject{};p.subject.type=AuthorizationSubjectType::USER;p.subject.userId=id;p.subject.authenticated=authenticated;}
void setSystemSubject(SubjectFake& p){p.subject=AuthorizationSubject{};p.subject.type=AuthorizationSubjectType::SYSTEM;p.subject.authenticated=true;}
}
void setUp(){}void tearDown(){}

void test_identity_common_and_subjects()
{TEST_ASSERT_EQUAL_UINT16(0U,INVALID_USER_ID);TEST_ASSERT_EQUAL_UINT16(0U,INVALID_ROLE_ID);PermissionMask seen=0ULL;for(uint8_t i=0U;i<(uint8_t)Permission::COUNT;++i){Permission p=(Permission)i;PermissionMask bit=permissionToMask(p);TEST_ASSERT_NOT_EQUAL(0ULL,bit);TEST_ASSERT_EQUAL_UINT64(0ULL,seen&bit);seen|=bit;TEST_ASSERT_TRUE(hasPermission(seen,p));}TEST_ASSERT_EQUAL_UINT64(0ULL,permissionToMask((Permission)99U));TEST_ASSERT_TRUE(isValidPermissionMask(NO_PERMISSIONS));TEST_ASSERT_TRUE(isValidPermissionMask(seen));if((uint8_t)Permission::COUNT<64U)TEST_ASSERT_FALSE(isValidPermissionMask(PermissionMask{1ULL}<<(uint8_t)Permission::COUNT));AuthorizationSubject s;TEST_ASSERT_FALSE(s.isValid());s.type=AuthorizationSubjectType::USER;TEST_ASSERT_FALSE(s.isValid());s.userId=1U;s.authenticated=true;TEST_ASSERT_TRUE(s.isValid());s.type=AuthorizationSubjectType::SYSTEM;TEST_ASSERT_FALSE(s.isValid());s.userId=INVALID_USER_ID;TEST_ASSERT_TRUE(s.isValid());}

void test_user_and_role_value_types()
{User u;TEST_ASSERT_FALSE(u.isValid());u=makeUser(1U,1U,false);TEST_ASSERT_TRUE(u.isValid());u.roleId=INVALID_ROLE_ID;TEST_ASSERT_FALSE(u.isValid());Role r;TEST_ASSERT_FALSE(r.isValid());r=makeRole(1U,NO_PERMISSIONS,false);TEST_ASSERT_TRUE(r.isValid());r.permissions=permissionToMask(Permission::QUERY);TEST_ASSERT_TRUE(r.hasPermission(Permission::QUERY));TEST_ASSERT_FALSE(r.hasPermission(Permission::MANAGE_USERS));r.permissions=1ULL<<(uint8_t)Permission::COUNT;TEST_ASSERT_FALSE(r.isValid());}

void test_user_registry_atomic_contiguous_operations()
{UserRegistry reg;TEST_ASSERT_EQUAL_UINT32(0U,reg.size());TEST_ASSERT_EQUAL_UINT32(USER_REGISTRY_CAPACITY,reg.capacity());User invalid;TEST_ASSERT_EQUAL_UINT8((uint8_t)UserRegistryResult::INVALID_USER,(uint8_t)reg.add(invalid));for(UserId i=1U;i<=USER_REGISTRY_CAPACITY;++i)TEST_ASSERT_EQUAL_UINT8(0U,(uint8_t)reg.add(makeUser(i,1U)));TEST_ASSERT_EQUAL_UINT8((uint8_t)UserRegistryResult::USER_ALREADY_EXISTS,(uint8_t)reg.add(makeUser(1U,2U)));TEST_ASSERT_EQUAL_UINT8((uint8_t)UserRegistryResult::REGISTRY_FULL,(uint8_t)reg.add(makeUser(99U,1U)));TEST_ASSERT_EQUAL_UINT32(USER_REGISTRY_CAPACITY,reg.size());User updated=makeUser(2U,3U,false);TEST_ASSERT_EQUAL_UINT8(0U,(uint8_t)reg.update(updated));TEST_ASSERT_EQUAL_UINT16(3U,reg.find(2U)->roleId);TEST_ASSERT_EQUAL_UINT8((uint8_t)UserRegistryResult::USER_NOT_FOUND,(uint8_t)reg.update(makeUser(99U)));TEST_ASSERT_EQUAL_UINT8(0U,(uint8_t)reg.remove(1U));TEST_ASSERT_EQUAL_UINT16(2U,reg.find(2U)->id);TEST_ASSERT_EQUAL_UINT8((uint8_t)UserRegistryResult::USER_NOT_FOUND,(uint8_t)reg.remove(99U));TEST_ASSERT_NULL(reg.find(99U));reg.clear();TEST_ASSERT_EQUAL_UINT32(0U,reg.size());}

void test_role_registry_atomic_contiguous_operations()
{RoleRegistry reg;TEST_ASSERT_EQUAL_UINT32(ROLE_REGISTRY_CAPACITY,reg.capacity());Role invalid;TEST_ASSERT_EQUAL_UINT8((uint8_t)RoleRegistryResult::INVALID_ROLE,(uint8_t)reg.add(invalid));for(RoleId i=1U;i<=ROLE_REGISTRY_CAPACITY;++i)TEST_ASSERT_EQUAL_UINT8(0U,(uint8_t)reg.add(makeRole(i)));TEST_ASSERT_EQUAL_UINT8((uint8_t)RoleRegistryResult::ROLE_ALREADY_EXISTS,(uint8_t)reg.add(makeRole(1U)));TEST_ASSERT_EQUAL_UINT8((uint8_t)RoleRegistryResult::REGISTRY_FULL,(uint8_t)reg.add(makeRole(99U)));Role updated=makeRole(2U,permissionToMask(Permission::QUERY),false);TEST_ASSERT_EQUAL_UINT8(0U,(uint8_t)reg.update(updated));TEST_ASSERT_FALSE(reg.find(2U)->enabled);TEST_ASSERT_EQUAL_UINT8(0U,(uint8_t)reg.remove(1U));TEST_ASSERT_EQUAL_UINT16(2U,reg.find(2U)->id);TEST_ASSERT_EQUAL_UINT8(0U,(uint8_t)reg.add(makeRole(99U)));TEST_ASSERT_NOT_NULL(reg.find(99U));TEST_ASSERT_EQUAL_UINT8((uint8_t)RoleRegistryResult::ROLE_NOT_FOUND,(uint8_t)reg.remove(100U));reg.clear();TEST_ASSERT_EQUAL_UINT32(0U,reg.size());}

void test_policy_base_subject_and_provider_failures()
{UserRegistry users;RoleRegistry roles;SubjectFake provider;RuntimeAuthorizationPolicy policy(provider,users,roles);Command invalid;TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::INVALID_REQUEST,(uint8_t)policy.check(invalid,1U));Command c=makeCommand();c.context.risk=(CommandRisk)99U;TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::POLICY_ERROR,(uint8_t)policy.check(c,1U));TEST_ASSERT_EQUAL_UINT16(0U,provider.calls);c=makeCommand();provider.result=(AuthorizationCheckResult)99U;TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::POLICY_ERROR,(uint8_t)policy.check(c,1U));provider.result=AuthorizationCheckResult::POLICY_ERROR;TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::POLICY_ERROR,(uint8_t)policy.check(c,1U));provider.result=AuthorizationCheckResult::ALLOWED;provider.subject=AuthorizationSubject{};TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::INVALID_REQUEST,(uint8_t)policy.check(c,1U));setUserSubject(provider,1U,false);TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::UNAUTHORIZED,(uint8_t)policy.check(c,1U));setSystemSubject(provider);TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::ALLOWED,(uint8_t)policy.check(c,1U));}

void test_policy_user_role_fail_closed_paths()
{UserRegistry users;RoleRegistry roles;SubjectFake provider;setUserSubject(provider);RuntimeAuthorizationPolicy policy(provider,users,roles);Command c=makeCommand();TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::USER_NOT_FOUND,(uint8_t)policy.check(c,1U));users.add(makeUser(1U,1U,false));TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::USER_DISABLED,(uint8_t)policy.check(c,1U));users.update(makeUser());TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::PERMISSION_DENIED,(uint8_t)policy.check(c,1U));roles.add(makeRole(1U,permissionToMask(Permission::EXECUTE_ACTION),false));TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::PERMISSION_DENIED,(uint8_t)policy.check(c,1U));roles.update(makeRole(1U,NO_PERMISSIONS,true));TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::PERMISSION_DENIED,(uint8_t)policy.check(c,1U));roles.update(makeRole(1U,permissionToMask(Permission::EXECUTE_ACTION),true));TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::ALLOWED,(uint8_t)policy.check(c,1U));}

void test_permission_mapping_for_risk_query_and_domains()
{UserRegistry users;RoleRegistry roles;SubjectFake provider;setUserSubject(provider);users.add(makeUser());RuntimeAuthorizationPolicy policy(provider,users,roles);struct Case{CommandDomain domain;CommandRisk risk;Permission permission;};const Case cases[]={{CommandDomain::OUT,CommandRisk::ACTION,Permission::EXECUTE_ACTION},{CommandDomain::OUT,CommandRisk::SENSITIVE,Permission::EXECUTE_SENSITIVE},{CommandDomain::OUT,CommandRisk::DANGEROUS,Permission::EXECUTE_DANGEROUS},{CommandDomain::CFG,CommandRisk::ACTION,Permission::MANAGE_CONFIG},{CommandDomain::STORE,CommandRisk::ACTION,Permission::MANAGE_STORAGE},{CommandDomain::USER,CommandRisk::ACTION,Permission::MANAGE_USERS},{CommandDomain::SYS,CommandRisk::ACTION,Permission::MANAGE_SYSTEM},{CommandDomain::NODE,CommandRisk::ACTION,Permission::MANAGE_NODES},{CommandDomain::SCN,CommandRisk::ACTION,Permission::EXECUTE_SCENES},{CommandDomain::RULE,CommandRisk::ACTION,Permission::EXECUTE_RULES},{CommandDomain::SCH,CommandRisk::ACTION,Permission::MANAGE_SCHEDULES},{CommandDomain::SMS,CommandRisk::ACTION,Permission::USE_SMS},{CommandDomain::CALL,CommandRisk::ACTION,Permission::USE_CALL}};for(const Case& item:cases){roles.clear();roles.add(makeRole(1U,permissionToMask(item.permission)));TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::ALLOWED,(uint8_t)policy.check(makeCommand(item.domain,item.risk),1U));}roles.clear();roles.add(makeRole(1U,permissionToMask(Permission::QUERY)));TEST_ASSERT_EQUAL_UINT8((uint8_t)AuthorizationCheckResult::ALLOWED,(uint8_t)policy.check(makeQuery(),1U));}

void test_policy_does_not_mutate_command()
{UserRegistry users;RoleRegistry roles;SubjectFake provider;setSystemSubject(provider);RuntimeAuthorizationPolicy policy(provider,users,roles);Command c=makeCommand();unsigned char before[sizeof(Command)];memcpy(before,&c,sizeof(c));TEST_ASSERT_EQUAL_UINT8(0U,(uint8_t)policy.check(c,5U));TEST_ASSERT_EQUAL_INT(0,memcmp(before,&c,sizeof(c)));TEST_ASSERT_EQUAL_UINT16(1U,provider.calls);}

void test_composite_gate_runtime_authorization_integration()
{UserRegistry users;RoleRegistry roles;SubjectFake provider;setUserSubject(provider);users.add(makeUser());roles.add(makeRole(1U,permissionToMask(Permission::EXECUTE_ACTION)));RuntimeAuthorizationPolicy policy(provider,users,roles);ModeFake mode;SafetyFake safety;TokenFake token;CompositeCommandExecutionGate gate(mode,policy,safety,token);Command c=makeCommand();TEST_ASSERT_EQUAL_UINT8((uint8_t)CommandExecutionGateResult::ALLOWED,(uint8_t)gate.check(c,1U));roles.update(makeRole(1U,NO_PERMISSIONS));TEST_ASSERT_EQUAL_UINT8((uint8_t)CommandExecutionGateResult::UNAUTHORIZED,(uint8_t)gate.check(c,1U));TEST_ASSERT_EQUAL_UINT8(1U,token.checks);TEST_ASSERT_EQUAL_UINT8(1U,safety.calls);users.update(makeUser(1U,1U,false));TEST_ASSERT_EQUAL_UINT8((uint8_t)CommandExecutionGateResult::UNAUTHORIZED,(uint8_t)gate.check(c,1U));setSystemSubject(provider);TEST_ASSERT_EQUAL_UINT8((uint8_t)CommandExecutionGateResult::ALLOWED,(uint8_t)gate.check(c,1U));}

void setup(){UNITY_BEGIN();RUN_TEST(test_identity_common_and_subjects);RUN_TEST(test_user_and_role_value_types);RUN_TEST(test_user_registry_atomic_contiguous_operations);RUN_TEST(test_role_registry_atomic_contiguous_operations);RUN_TEST(test_policy_base_subject_and_provider_failures);RUN_TEST(test_policy_user_role_fail_closed_paths);RUN_TEST(test_permission_mapping_for_risk_query_and_domains);RUN_TEST(test_policy_does_not_mutate_command);RUN_TEST(test_composite_gate_runtime_authorization_integration);UNITY_END();}void loop(){}
